# Site Settings
title: DDoS-v3
author: Hyperclaw79
description: Asynchronous HTTP Botnet for Distributed Denial of Service (DDoS)
url: https://hyperclaw79.github.io/DDoS-v3
# Build Settings
theme: jekyll-theme-hacker
markdown: GFM
plugins:
  - jekyll-seo-tag
  - jemoji
